import configureMockStore from 'redux-mock-store';
import thunk from 'redux-thunk';
import { addExpense, editExpense, removeExpense, startAddExpense } from '../../actions/expenses';
import expenses from '../fixtures/expenses';
import database from '../../firebase/firebase';

// Use configureMockStore and give a thunk middleware
const createMockStore = configureMockStore([thunk]);

test('Should setup remove action object', () => {
    const action = removeExpense({ id: '123abc' }); 
    expect(action).toEqual({
        type: 'REMOVE_EXPENSE',
        id: '123abc'
    });
});

test('Should setup edit action object', () => {
    const action = editExpense('123abc',{ note: 'some notes'}); 
    expect(action).toEqual({
        type: 'EDIT_EXPENSE',
        id: '123abc',
        updates: {
            note: 'some notes'
        }
    });
});

test('Should setup add expense action object with provided value', () => {
    const action = addExpense(expenses[2]);
    expect(action).toEqual({
        type: 'ADD_EXPENSE',
        expense: expenses[2]
    });
});

test('Should add expense to database and store', (done) => {
    const store = createMockStore({});
    const expenseData = {
        description: 'Mouse',
        amount: 8000,
        note: 'This one is better',
        createdAt: 3000
    };

    store.dispatch(startAddExpense(expenseData)).then(() => {
        const actions = store.getActions();
        expect(actions[0]).toEqual({
            type: 'ADD_EXPENSE',
            expense: {
                id: expect.any(String),
                ...expenseData
            }
        });

        // This id is generated by firebase
        return database.ref(`expenses/${actions[0].expense.id}`).once('value');  
    }).then((snapshot) => {
        expect(snapshot.val()).toEqual(expenseData);
        done(); // Since this test is asynchronous, we need to tell jest when it's done.
    });
});

test('Should add default expense to database and store', (done) => {
    const store = createMockStore({});
    const expenseDefaults = {
        description: '',
        note: '',
        amount: 0,
        createdAt: 0
    };

    store.dispatch(startAddExpense({})).then(() => {
        const actions = store.getActions();
        expect(actions[0]).toEqual({
            type: 'ADD_EXPENSE',
            expense: {
                id: expect.any(String),
                ...expenseDefaults
            }
        });

        // This id is generated by firebase
        return database.ref(`expenses/${actions[0].expense.id}`).once('value');  
    }).then((snapshot) => {
        expect(snapshot.val()).toEqual(expenseDefaults);
        done(); 
    });
});

// test('Should setup add expense action object with default value', () => {
//     const expenseData = {
//         description: '',
//         amount: 0,
//         createdAt: 0,
//         note: ''
//     };
//     const action = addExpense();
//     expect(action).toEqual({
//         type: 'ADD_EXPENSE',
//         expense: {
//             ...expenseData,
//             id: expect.any(String)
//         }
//     });
// });